[build]
  command = "npm install && npm install -g vite && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
