[build]
  command = "npm install --no-audit && npm install vite@5.4.1 @vitejs/plugin-react-swc autoprefixer tailwindcss postcss @tailwindcss/postcss --no-audit && npx vite build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  CI = "false"
  NPM_FLAGS = "--legacy-peer-deps"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
